# Generated by Django 6.0.4 on 2026-05-05 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ILES_app', '0002_user_is_approved'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
