# Generated by Django 6.0.4 on 2026-05-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ILES_app', '0004_evaluation_student_confirmed_view_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipplacement',
            name='exception_request_type',
            field=models.CharField(blank=True, choices=[('count_existing', 'Count Existing Only'), ('late_submission', 'Request Late Submission')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='internshipplacement',
            name='workplace_decision_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='internshipplacement',
            name='workplace_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
